Fixes image_size parameter for training, works for powers of 2 >= 8
bamos/dcgan-completion.tensorflow pull request #46
Opened 2017-06-25 06:16 UTC by md5wasp

I was not able to get the image_size parameter working when training, it seemed like the code had some hardcoded assumptions about the image size in the generator.

This PR fixes that, but only for cases where the image is square with side lengths that are a power of 2, that is 8 pixels or more.

The generator is parameterised based on the image size, with more upscale/transpose convolutions for more powers of 2.

My assumption is that larger images require more complex models in the discriminator. However, I have not yet found a way to effectively parameterise the discriminator to scale with image size. For now it still works OK for me up to 128, which is as high as I can do with my limited GPU memory.

Other small changes:

- Removes the hardcoded requirement for png images to be input. Maybe don't accept this PR if you don't want people's existing command line args to break (now just uses the glob, rather than accepting a directory).
 - Fixes directory creation on python 2.7
 - Deleted one or two lines of commented code.
 - Turned data shuffling back on.

I won't be offended if you don't accept this PR :) I'm not even close to being an expert. Thank you so much for the original code!

2017-06-26 12:27 UTC, bamos commented
Thanks! This mostly looks great. I added a few minor review comments we should change before merging this in

2017-06-27 10:10 UTC, md5wasp commented
I think maybe I need to l2github, because I can't quite find your comments!

2017-06-27 12:54 UTC, bamos requested changes

2017-06-27 12:54 UTC, bamos commented on model.py
> +            batch_norm(name='d_bn%d' % (i,)) for i in range(4)]
Let's use `.format` instead

2017-06-27 12:54 UTC, bamos commented on model.py
> +        data = glob(config.dataset)
Can you modify this (and the one below) to keep the old behavior while also adding the new behavior you want? If you want to support other image extensions, add them to the glob

2017-06-27 12:55 UTC, bamos commented
Ah oops, I didn't realize that I needed to submit the comments for you to see them. :)

2017-06-29 11:28 UTC, md5wasp commented on model.py
> +        data = glob(config.dataset)
OK, I've put it back to just accepting a folder and inserting the glob in the code, but now it supports png and jpg/jpeg. Currently that's hardcoded, would you prefer the supported file types to be a parameter to the constructor instead?

2017-07-02 10:29 UTC, bamos commented
Thanks! This looks great now.

2017-07-02 10:29 UTC, merged